### ISSUE TITLE
Hardcoded retry attempts

### ISSUE THREAD

**Issue by dosoft** [aklajnert/idasen-control#10]
```
if attempt > 3 {
```

Could u please make it configurable? For some reason (I dunno why) 3 is not enough for me sometimes.

**Comment by aklajnert** [comment]
Hmm, this was quite recently doubled within the underlying crate. But I think it shouldn't be too much work to implement that.  
I'll look at it when I'll find some time, or feel free to try implementing it yourself and submit a PR.
